/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Edge {
  
  @SerializedName("id")
  private UUID id = null;
  @SerializedName("head")
  private UUID head = null;
  @SerializedName("tail")
  private UUID tail = null;
  @SerializedName("class")
  private String _class = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getHead() {
    return head;
  }
  public void setHead(UUID head) {
    this.head = head;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getTail() {
    return tail;
  }
  public void setTail(UUID tail) {
    this.tail = tail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getClass() {
    return _class;
  }
  public void setClass(String _class) {
    this._class = _class;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Edge edge = (Edge) o;
    return (this.id == null ? edge.id == null : this.id.equals(edge.id)) &&
        (this.head == null ? edge.head == null : this.head.equals(edge.head)) &&
        (this.tail == null ? edge.tail == null : this.tail.equals(edge.tail)) &&
        (this._class == null ? edge._class == null : this._class.equals(edge._class));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.head == null ? 0: this.head.hashCode());
    result = 31 * result + (this.tail == null ? 0: this.tail.hashCode());
    result = 31 * result + (this._class == null ? 0: this._class.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Edge {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  head: ").append(head).append("\n");
    sb.append("  tail: ").append(tail).append("\n");
    sb.append("  _class: ").append(_class).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
