/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.NodeEdge;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003In {
  
  @SerializedName("5f9e769ff6fe4cee02b3b4547200db6b")
  private NodeEdge _5f9e769ff6fe4cee02b3b4547200db6b = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public NodeEdge get5f9e769ff6fe4cee02b3b4547200db6b() {
    return _5f9e769ff6fe4cee02b3b4547200db6b;
  }
  public void set5f9e769ff6fe4cee02b3b4547200db6b(NodeEdge _5f9e769ff6fe4cee02b3b4547200db6b) {
    this._5f9e769ff6fe4cee02b3b4547200db6b = _5f9e769ff6fe4cee02b3b4547200db6b;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003In inlineResponse2003In = (InlineResponse2003In) o;
    return (this._5f9e769ff6fe4cee02b3b4547200db6b == null ? inlineResponse2003In._5f9e769ff6fe4cee02b3b4547200db6b == null : this._5f9e769ff6fe4cee02b3b4547200db6b.equals(inlineResponse2003In._5f9e769ff6fe4cee02b3b4547200db6b));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this._5f9e769ff6fe4cee02b3b4547200db6b == null ? 0: this._5f9e769ff6fe4cee02b3b4547200db6b.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003In {\n");
    
    sb.append("  _5f9e769ff6fe4cee02b3b4547200db6b: ").append(_5f9e769ff6fe4cee02b3b4547200db6b).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
