/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.InlineResponse2003In;
import io.swagger.client.model.NodeEdge;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse2003 {
  
  @SerializedName("from")
  private List<NodeEdge> from = null;
  @SerializedName("to")
  private List<NodeEdge> to = null;
  @SerializedName("in")
  private List<InlineResponse2003In> in = null;
  @SerializedName("out")
  private List<InlineResponse2003In> out = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<NodeEdge> getFrom() {
    return from;
  }
  public void setFrom(List<NodeEdge> from) {
    this.from = from;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<NodeEdge> getTo() {
    return to;
  }
  public void setTo(List<NodeEdge> to) {
    this.to = to;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<InlineResponse2003In> getIn() {
    return in;
  }
  public void setIn(List<InlineResponse2003In> in) {
    this.in = in;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<InlineResponse2003In> getOut() {
    return out;
  }
  public void setOut(List<InlineResponse2003In> out) {
    this.out = out;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return (this.from == null ? inlineResponse2003.from == null : this.from.equals(inlineResponse2003.from)) &&
        (this.to == null ? inlineResponse2003.to == null : this.to.equals(inlineResponse2003.to)) &&
        (this.in == null ? inlineResponse2003.in == null : this.in.equals(inlineResponse2003.in)) &&
        (this.out == null ? inlineResponse2003.out == null : this.out.equals(inlineResponse2003.out));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.from == null ? 0: this.from.hashCode());
    result = 31 * result + (this.to == null ? 0: this.to.hashCode());
    result = 31 * result + (this.in == null ? 0: this.in.hashCode());
    result = 31 * result + (this.out == null ? 0: this.out.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("  from: ").append(from).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("  in: ").append(in).append("\n");
    sb.append("  out: ").append(out).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
